version: '{branch}-{build}'

branches:
  only:
    - rewrite

skip_tags: true

only_commits:
  files:
    - RakDotNet/
    - Uchu.Auth/
    - Uchu.Char/
    - Uchu.Core/
    - Uchu.Master/
    - Uchu.StandardScripts/
    - Uchu.World/
    - .appveyor.yml
    - .gitmodules
    - Uchu.sln

image:
  - Visual Studio 2019
  - Ubuntu1604
  - Ubuntu1804

clone_depth: 1

cache:
  - packages -> **/*.csproj

install:
  - git submodule update --init --recursive
  - dotnet restore

configuration: Release

build:
  parallel: true
  project: Uchu.sln

artifacts:
  - path: Uchu.Auth/bin/
    name: UchuAuth
  - path: Uchu.Char/bin/
    name: UchuChar
  - path: Uchu.World/bin/
    name: UchuWorld
  - path: Uchu.Master/bin/
    name: UchuMaster