version: '{branch}-{build}'

branches:
  only:
    - master

skip_tags: true

skip_commits:
  files:
    - README.md
    - CODE_OF_CONDUCT.md
    - .gitignore
    - .gitattributes

image:
  - Visual Studio 2019
  - Ubuntu1804

clone_depth: 1

cache:
  - packages -> **/*.csproj
  - '~/.local/share/NuGet/v3-cache'
  - '~/.local/share/NuGet/Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%LocalAppData%\NuGet\Cache'

install:
  - git submodule update --init --recursive
  - dotnet restore

configuration: Release

build:
  parallel: false
  project: Uchu.sln

artifacts:
  - path: Uchu.Auth/bin/${configuration}/
    name: UchuAuth
  - path: Uchu.Char/bin/${configuration}/
    name: UchuChar
  - path: Uchu.World/bin/${configuration}/
    name: UchuWorld
  - path: Uchu.Master/bin/${configuration}/
    name: UchuMaster
  - path: Uchu.Instance/bin/${configuration}/
    name: UchuInstance
  - path: Uchu.StandardScripts/bin/${configuration}
    name: UchuStandardScripts

notifications:
  - provider: Webhook
    url: https://uchu-builds-webhook.herokuapp.com/webhook/appveyor
    method: POST
